Additions/UIView-KIFAdditions.m

Iterating over UICollectionView cells could lead to an accumulation of
cells object (and therefore an increase of memory).
This commit adds an autoreleasepool to mitigate the problem and force
the release of the cell objects.

Add autoreleasepool to prevent memory peak

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m

Allows to specify a waiting timeout without having to modify the global animationWaitingTimeout

Add waitForAnimationsToFinishWithTimeout method

---

Classes/KIFUITestActor.m

The analyzer complains as rowTitle might be nil if the delegate responds to neither of the tested methods.
Original warning: Argument to 'NSMutableArray' method 'addObject:' cannot be nil
Adding the assert appeases the analyzer and has the added advantage to give a more helpful error message if that case occurs instead of just crashing with "trying to insert nil".

Fixed an analyzer warning

---

Classes/KIFUITestActor.m

The analyzer warning fix proposed in #557 works fine when ENABLE_NS_ASSERTIONS=YES. But if assertions are disabled (which is the case when integrating KIF with CocoaPods) the analyzer warning comes back.

Fix analyzer warning regardless of `ENABLE_NS_ASSERTIONS` setting

---

KIF.xcodeproj/project.pbxproj

Similar fix to kif-framework#420, but when being used without CocoaPods (e.g. Git submodules).

Add workaround for error finding XCTest.h

---

Classes/KIFTestCase.m

To fix the issue https://github.com/kif-framework/KIF/issues/524.

Replace `performTest` call with `performSelector` when calling `beforeAll` and `afterAll` methods.

---

Additions/UIEvent+KIFAdditions.h
Additions/UIEvent+KIFAdditions.m
Additions/UIView-KIFAdditions.m
KIF.xcodeproj/project.pbxproj

Tentative fix for https://github.com/kif-framework/KIF/issues/574
Running KIF on iOS 8.3 (with XCode 6.3 Beta) leads to the following error
Since it was referencing `IOHIDEvent` I looked into `[UIEvent _hidEvent]` [private attribute](https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/UIKit.framework/UIEvent.h#L15) and realized it was always nil for [UIEvent created by KIF](https://github.com/kif-framework/KIF/blob/a98d4102e6ee1f11e7fc88bf99ab724baf320ce5/Additions/UIView-KIFAdditions.m#L782) (unlike real UIEvents that have a valid `_hidEvent`).
My guess was that starting with iOS 8.3, the usage of `[UIEvent _gsEvent]` was deprecated in favor on `[UIEvent _hidEvent]`.
After some poking around, trial and error and the help of [some …

Make touch UIEvent compatible with iOS 8.3

---

Classes/KIFSystemTestActor.h
Classes/KIFSystemTestActor.m
KIF Tests/SystemTests.m

This is useful for making an assertion that an app switches to a
particular app.
It has the benefit of being less technically prescriptive than a fully specified absolute URL,
but still more valuable in tests than a the more general assertion on _any_ URL.

Add URL Matcher for asserting on URL scheme

---

Classes/KIFUITestActor.m

Added the fix for the waitForCellAtIndexPath method, as mentioned in issue #583. I didn't find it necessary to reload the data, so I left that out.

Fixed #583, waitForCellAtIndexPath:inCollectionView

---

Additions/UIView-KIFAdditions.m

In my case, the UICollectionView was being searched for a cell, but was scrolling to a cell who's frame size was 0 over and over again. This PR fixes infinite recursion in those cases.

Fixes issue #464 (infinite recursion in UICollectionView)

---

README.md

Hello! I noticed the Objective-C code in the README wasn't syntax highlighted, but the other code blocks were. This PR fixes that!

Syntax highlight Objective-C in README

---

Additions/UIView-KIFAdditions.h
Additions/UIView-KIFAdditions.m

It prints the view hierarchy along with KIF related information, like the accessibility label or identifier, whether the view is visible or not etc.. I found it quite useful for debugging when the waitForView... methods fail for unknown reasons. 
The methods comes in two variants, an instance method which prints the hierarchy starting with the given view and a class method, called with ```[UIView printViewHierarchy]``` which starts with the top window(s) and prints all the subviews from there.

Added printViewHierarchy to the UIView category. 

---

IdentifierTests/KIFUITestActor-IdentifierTests.h
IdentifierTests/KIFUITestActor-IdentifierTests.m
KIF Tests/AccessibilityIdentifierTests.m

Add the ability to test whether an element is visible on the screen based on the accessibilityIdentifier. This pull request attempts to add that.

Add identifier test: isElementWithAccessibilityIdentifierVisible

---

Additions/UIApplication-KIFAdditions.h
Additions/UIApplication-KIFAdditions.m
Classes/KIFSystemTestActor.m
KIF Tests/SystemTests.m

This further enhances the behavior introduced in
https://github.com/kif-framework/KIF/pull/588
When mocking openURL:, it also makes sense to be able to call
canOpenURL: and receive consistent results.
For example:
```objectivec
[system waitForApplicationToOpenURL:@"test123://" whileExecutingBlock:^{
NSURL *URL = [NSURL URLWithString:@"test123://"];
NSAssert([[UIApplication sharedApplication] openURL:URL],
@"You can open the URL");
NSAssert([[UIApplication sharedApplication] canOpenURL:URL],
@"You can also check the URL");
} returning:YES];
```
- Whenever openURL: is swizzled, also swizzle canOpenURL:
- When canOpenURL: is called, an NSNotification is posted
- The notification handler checks whether the URL matches,
- possibly failing the test,
- but leaving the openURL: mocking in place

Add ability to call canOpenURL: during waitForApplicationToOpenURL blocks

---

Additions/UIEvent+KIFAdditions.m

The current implementation for the gesture `timeStamp` uses the `mach_absolute_time()`.  This poses a problem because the Static Analyzer can't correctly cast `mach_absolute_time` to `AbsoluteTime` resulting in a Static Analyzer Issue.
This solution replaces `AbsoluteTime` with with `CFAbsoluteTime` and then uses the  `CACurrentMediaTime` [which is also based off of the internal clock](http://nshipster.com/benchmarking/) to set the timeStamp.

Fixed static analysis error with uninitialized data

---

Additions/UIEvent+KIFAdditions.m
Additions/UIView-KIFAdditions.m

This little fix is related to **UIPanGestureRecognizer**.
The main problem was that the _UIEvent_ object doesn\`t have a correct time stamp. That was always 0. If the time stamp is constant than the ```[panGestureRecognizer velocityInView:view]``` value remains always 0 on dragging the generated _UITouch_ objects from one point to another.
This fix synchronizes _UITouch_ and _UIEvent_ objects time stamp, and with this little change the system provides a valid velocity value when you call ```velocityInView:``` method.
Best regards,
LoGeN

Fixed: UIPanGestureRecognizer velocity value

---

Additions/UIView-KIFAdditions.m
KIF Tests/TableViewTests.m

The implict approach to finding accessibility elements in a table view
results in cells being instantiated and added as subviews of the table
view, despite not being visible. When the table view has many rows
with heavyweight cells this can cause severe memory pressure. This
commit uses a direct approach to find accessibility elements in table
views, which allows for proper removal of non-visible cells. It also
has the benefit of returning actual views instead of accessibility
elements.

Remove non-visible table view cells so that they don't stick around.

---

Additions/UIView-KIFAdditions.m

I added a small change to the printViewHierarchy method so it prints out the proper class name for an accessibility element.

Print the correct UIAccessibilityElement (sub)class name

---

IdentifierTests/KIFUITestActor-IdentifierTests.h
IdentifierTests/KIFUITestActor-IdentifierTests.m
KIF Tests/GestureTests.m
Test Host/en.lproj/MainStoryboard.storyboard

Test cases are also added for swipe up, down, left, right.
view identification takes place on the accessibility identifier
rather than the accessibilityLabel attribute.

Add swipeViewWithAccessibilityIdentifier method

---

KIF Tests/TableViewTests.m
Test Host/TableViewController.m

Added canEditRowAtIndexPath, editingStyleForRowAtIndexPath and commitEditingStyle methods to
TableViewController in order to support line editing.
Added unit test that swipes and deletes the first and last rows in the table view.

Added unit test for row swiping

---

KIF Tests/GestureTests.m
Test Host/GestureViewController.m
Test Host/en.lproj/MainStoryboard.storyboard

I implemented 4 new test cases for testing the UIPangestureRecognizer`s velocity value.

UIPanGestureRecognizer velocity test cases

---

.travis.yml

Travis has been flakey lately. Disabling iOS 7 support to make things easier to debug and test. Will likely re-enable soon.

Disable iOS 7 on Travis

---

Additions/UIView-KIFAdditions.m

Handle newlines in accessibility labels.

---

Additions/UIView-KIFAdditions.m

I bumped into a rare problem while trying to update to KIF 3.2.3
[UITableView indexPathsForVisibleRows] seems to return index paths for
non visible cells if screen folds on the tableview header.
I opened a radar with Apple. See http://openradar.appspot.com/radar?id=5191284490764288
To avoid this bug, we are now using the visibleCells method which
doesn't suffer from the same problem.
It won't be as fast as before since enumerating through the visible cells is necessary to get all the index paths but correctness is definitely the priority.
Let me know what you think. Thx

Use [UITableView visibleCells] instead of indexPathsForVisibleRows

---

Classes/KIFUITestActor.m

The compiler does not complain about this, but it's nice to be consistent about it!

Removing semicolons from method signatures

---

Classes/KIFUITestActor.m

The view must be tappable if you want to swipe on it.

View must be tappable when swipe is requested

---

Additions/UIApplication-KIFAdditions.m

When NULL is passed for the error pointer, this was causing a crash because there was no null pointer check.

Added null pointer check

---

Classes/KIFTestActor.h
Classes/KIFTestActor.m

Hi,
I'd like to introduce a new getter and setter for the `animationWaitingTimeout` property. In our KIF test suite we do something like this in `application:didFinishLaunchingWithOptions:`:
```objc
#ifdef EBK_DISABLE_ANIMATIONS
[UIView setAnimationsEnabled:NO];
#endif
```
This already decreased the execution time of our test suite dramatically. Without anymations enabled, we don't really need `animationWaitingTimeout = 0.5f`. If we could configure this from the outside, it would decrease the execution time even more.
Thanks,
plu

Add getter/setter for default animationWaitingTimeout

---

Additions/UIApplication-KIFAdditions.m

Some keywindows can be hidden in weird application implementations.
This fix attempts to avoid the crash.
https://github.com/kif-framework/KIF/issues/679

Fix for issue 679. Crash taking screenshot.

---

Additions/UIApplication-KIFAdditions.h
Additions/UIEvent+KIFAdditions.m
Additions/UITouch-KIFAdditions.m
Classes/IOHIDEvent+KIF.h
Classes/IOHIDEvent+KIF.m
Classes/KIFSystemTestActor.m
Classes/KIFTestActor.m
Classes/KIFUITestActor.m
KIF Tests/BackgroundTests.m
KIF Tests/KIF Tests-Info.plist
KIF Tests/SpecificControlTests.m
KIF Tests/TableViewTests.m
KIF Tests/TappingTests.m
KIF.xcodeproj/project.pbxproj
KIF.xcodeproj/xcshareddata/xcschemes/KIF Documentation.xcscheme
KIF.xcodeproj/xcshareddata/xcschemes/KIF-OCUnit.xcscheme
KIF.xcodeproj/xcshareddata/xcschemes/KIF.xcscheme
KIF.xcodeproj/xcshareddata/xcschemes/KIFFramework.xcscheme
KIFFramework/Info.plist
Test Host/TapViewController.m
Test Host/Test Host-Info.plist
Test Host/en.lproj/MainStoryboard.storyboard

The main change consists in setting a now required internal IOHIDEvent to UITouch objects. https://github.com/kif-framework/KIF/commit/43163c0ee6cfa8c91b67ead4049ae296a56f0e86
This is of course very fragile and I believe the long term solution would be to add support for the new UI Testing framework provided by Apple and rely on XCUIElement API to interact with UI elements, and getting rid of those private API calls that will break every time Apple will make changes.
While this change allows most of the tests to run on iOS 9, some tests are still failing. I added a `//TODO` to the tests that are not passing on iOS 9 at the moment. See https://github.com/TBonnin/KIF/commit/6f8e4dc1fdcf4acc7ea1c97ba585edc076cd7671
~~Also I noticed I need to have the Accessibility Inspector enabled for KIF …

Xcode 7 and iOS 9 support

---

Classes/KIFTestActor.m

@phatmann it looks like my testing skills are lacking and my previous PR is not 100% complete.
At the moment running tests from Xcode 7 in a ios 8 simulator doesn't work because accessibility labels are not enabled/accessible.
After more testing I realized the solution in this PR allows to simplify the [KIFTestActor _enableAccessibility] method by not checking if it is running in iOS 9 sim while being compatible with both Xcode 6 and Xcode 7 (and both iOS 8 and 9 simulators)
I have tested sucessfully: 
- Xcode 6.4 / iOS 8.4 sim
- Xcode 7b4 / iOS 8.4 sim
- Xcode 7b4 / iOS 9.0 sim (ignoring the 3 failures already documented)
- Xcode 7b5 / iOS 9.0 sim (ignoring the 3 failures already documented)
I could not run the test with Xcode 7b5 and iOS 8 sim since running non iOS 9 sim with beta 5 …

Enable Accessibility on both Xcode iOS 8 and 9 regardless of Xcode version

---

README.md

without the import KIF statement I was not able to build the project, despite the import in the bridging header

README Missing Info for Swift: add missing import of KIF framework to use in swift projects

---

Classes/KIFUITestActor.m
KIF Tests/TypingTests.m

Previous method was not working properly when entering unicode characters such as Emojis; see screenshot 1 (old) vs 2 (new) to see the wrong rendering. I could not manage to reproduce it with a unit test in KIF project (but it is on linphone-iphone...), but at least it renders correctly now.

KIFUITestActor.m: fix enterText method to support unicode characters such as Emojis

---

Classes/UIAutomationHelper.m
KIF Tests/BackgroundTests.m

-[UIATarget reactivateApp] was not rewritten for the new iOS 9 app switcher so we use a horrible hack to get the correct accessibility element.
There also seems to be an issue with the UIAApplication object returned by the `frontMostApp` method which has a nil name.
These hacks heavily rely on implementation detail of -[UIATarget deactivateApp] and -[UIATarget reactivateApp] and might break anytime.
Fixes #703

Workaround broken `deactivateAppForDuration:` in iOS 9

---

.travis.yml

* Use latest OS X image (Xcode 7)
* Run tests on multiple iOS versions (8.1, 8.2, 8,3, 8.4 and 9.0)
* Use xcpretty for a readable output
* Use gstdbuf for live output of test results

Improve testing on Travis

---

Classes/KIFAccessibilityEnabler.h
Classes/KIFAccessibilityEnabler.m
Classes/KIFTestActor.m
KIF.xcodeproj/project.pbxproj

This moves the code in KIFTestActor that enables the AX Inspector out to its own class that
is an XCTestObserver. When all tests finish, the AX Inspector is returned to its previous
state, saving a trip to the Settings app after every test.

Return the Accessbility Inspector to its previous state after tests

---

Classes/KIFAccessibilityEnabler.m

PR #727 uses feature only available with the iOS 9 SDK. This restores iOS 8 and earlier compatibility.

Restore iOS < 9 compatibility

---

Test Host/TestSuiteViewController.m

The test host needs to have the accessibility label turned on
for the PTR to work on the table by label.

Fix Pull To Refresh test case.

---

Classes/KIFAccessibilityEnabler.m

The following commits have regressed some accessibility issues for iOS < 9.
https://github.com/kif-framework/KIF/commit/927050d0a3e4178182570c560f646fa8a257bc52
https://github.com/kif-framework/KIF/commit/17a1bc86be31440d144902b1719ae549b173db03
Relevant discussion can be found: https://github.com/kif-framework/KIF/issues/596
ModalViewTests appear to be failing on master on both Xcode 6.3.2, iPad 2, iOS 8.1. and Xcode 7.1, iPad 2, iOS 9.1.

Fix accessibility enabler not activating on iOS version < 9

---

Additions/UIApplication-KIFAdditions.m
KIF Tests/UIApplicationKIFAdditionsTests.m
KIF.xcodeproj/project.pbxproj

The line number appended to the saved screenshot file name should be optional. Specify `0` or negative values to hide the appendage "`, line %lu`".
Added unit test.

Optional line number on screenshot file name

---

Classes/KIFUITestActor.m

This was causing a compiler warning about sending a void * to parameter of type KIFPullToRefreshTiming

Fixed passing nil as pullDownDuration

---

Additions/UIEvent+KIFAdditions.m
Additions/UITouch-KIFAdditions.m
Classes/IOHIDEvent+KIF.h

I also added the CF_RETURNS_RETAINED annotation, and then the static analyzer called out all of the leaks.

Fixed IOHIDEvent memory leak

---

Documentation/Examples/Testable Swift/Testable Swift.xcodeproj/project.pbxproj
Documentation/Examples/Testable Swift/Testable Swift.xcodeproj/xcshareddata/xcschemes/Testable Swift.xcscheme
Documentation/Examples/Testable Swift/Testable Swift/Info.plist
Documentation/Examples/Testable Swift/Testable Swift/MasterViewController.swift
Documentation/Examples/Testable Swift/Testable SwiftTests/Info.plist
Documentation/Examples/Testable Swift/Testable SwiftTests/SimpleSwiftTest.swift
README.md

Hi,
I've fixed 2 things of `Testable Swift` example.
1. It was broken like [this](https://github.com/kif-framework/KIF/issues/602).
2. It was need to change to the modern environment.
And Update `Use with Swift` in `README.md`
Wanbok.

Make sure 'Testable Swift' works without any warnings.

---

Classes/KIFUITestActor.m

Hardcoding header height is obviously not working when media picker view is embedded in another view. This PR does that automatically, but please confirm that it's the correct way of doing it... thanks!

Properly compute header height when media picker is within another view

---

KIF Tests/TableViewTests.m
Test Host/TableViewController.m

It looks like the accessibility behavior on iOS 9.0 had a bug. I tried locally and could reproduce against the 9.0 simulator, but not against the 9.1 or 9.2 simulator. I've adjusted the app behavior to account for the platform bug.

Fix tableview tests (causing Travis to be red)

---

KIF Tests/GestureTests.m

Some tests would fail when run individually (when the navigation controller push animation is still happening), fixed that with a sleep in the beforeAll.
Also, `testScrolling` was failing consistently on the iPhone 6 Plus. It was dragging from the left edge of the screen which was triggering the navigation controller's `interactivePopGestureRecognizer`. The edge swipe region seems significantly bigger on iPhone 6 Plus.

Make gesture tests more reliable

---

KIF Tests/SpecificControlTests.m
KIF Tests/SystemAlertTests.m

I see the console logs with "AX Lookup problem! 22 com.apple.iphone.axserver:-1" against the iOS7 simulator. I'm running Xcode 6.4 on Yosemite against the 7.1 simulator.
Did this ever work on iOS7 simulators? Maybe we should do something to prevent it from being used on iOS7, like assert in that method itself? Would that make the contract more clear?

Don't run acknowledgeSystemAlert tests on iOS7, it doesn't work

---

Classes/KIFTestActor.h
Classes/KIFTestActor.m

We're using this as a convenience method to generate screenshots when test cases fail. It seemed like something that was reasonable to push upstream, but happy to keep it in our code if it wouldn't be useful for others.

Add a convenience method for logging an error

---

Classes/KIFUITestActor.m

This is causing the typing tests to fail on iOS7:
https://travis-ci.org/kif-framework/KIF/jobs/103960958

If an element is already first responder, don't tap it again

---

Classes/KIFUITestActor.m

We were hitting build errors when building for device. This is already not exposed in the header, so we're just also not compiling it in the source file on the same conditional.

Don't compile acknowledgeSystemAlert for device builds

---

Classes/KIFUITestActor.m

We had a case where we're tapping an element that displays a popover control, and it doesn't report as being firstResponder until after the popover has been displayed (on the next runloop cycle). Using KIFTestCondition here meant that we'd fail the immediate check, despite the element becoming first responder shortly thereafter.
The fix here is to allow the element to become first responder shortly after being tapped. This will make failures take a little longer (I limited it to a half second) if the element is tapped and doesn't ever become first responder.

Setting first responder on an accessibility element may be delayed

---

Additions/UIView-KIFAdditions.m

Added a fallthrough to allow UIControl subclasses to contain views with userInteractionEnabled == NO
We already have two specific special cases (which we should retain) but this one is more generic and will help with custom UIControls.
The logic is slightly different. Since we cant guarantee that a view of a given class is inside a UIControl, rather than walking to the top and evaluating that view, this will walk up the chain and evaluate every step along the way.

UIControl isUserInteractionEnabled check.

---

Additions/CALayer-KIFAdditions.h
Additions/CALayer-KIFAdditions.m
Classes/KIFUITestActor.m
KIF.podspec
KIF.xcodeproj/project.pbxproj
README.md

The fix goes recursively through all sublayers of the current view's layer.
I've implemented the fix as a block to keep the changes to a minimum but this can easily be changed to a method, perhaps in a similar fashion to
```obj-c
- (void)performBlockOnDescendentViews:(void (^)(UIView *view, BOOL *stop))block
```
Comments are welcome.

Fix for issue #789: waitForAnimationsToFinish animations on sublayers

---

Classes/KIFUITestActor.h

Fixing inconsistency in documentation parameter name and method name that causes a warning when CLANG_WARN_DOCUMENTATION_COMMENTS is enabled.

Fixing document warning

---

Classes/UIAutomationHelper.h
Classes/UIAutomationHelper.m
KIF Tests/SystemAlertTests.m

Because the system will only pop the system alerts once per simulator, we cant assert that they will pop on every test run. This PR fixes acknowledgeSystemAlert to ensure the alert is valid before we attempt to tap the dismissal button (avoiding a crasher), and updates the associated tests to only assert that the _final_ alert dismissal returns NO.

Fixing acknowledgeSystemAlert for dirty simulators.

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
IdentifierTests/KIFUITestActor-IdentifierTests.m

This commit adds a few convenience methods for cases in which an element only has an accessibility hint but no label or identifier. I'd like to get some early feedback on whether or not something like this would be appreciated. I think for clients it's more handy to use these methods instead of fiddling with `NSPredicate`.
The commit also adds a generic `waitForAbsenceOfViewWithElementMatchingPredicate` method which did not exist before.

Add method for waiting for the absence of a view identified through a predicate

---

README.md

`exclusive` will be removed from [CocoaPods 1.0 Migration](http://blog.cocoapods.org/CocoaPods-1.0/).

CocoaPods 1.0 Migration

---

.travis.yml
scripts/ci.sh

The exit on the end of the first command prevented the second one from running.

Fix Travis script to run both configs

---

Classes/KIFAccessibilityEnabler.h
Classes/KIFAccessibilityEnabler.m
Classes/KIFTestActor.m
Classes/KIFTestCase.m

It turns out that if you don't ensure that `XCTestObservationCenter` has already loaded, then attempting to use it and add an observer subverts some sort of internal setup required to get `XCTest` to spit out log lines during your tests like this:
> Test Case -[MyTestTarget.testOne testMethodOne] started.
This is a really big problem if you rely on something like `xcpretty` parsing this output from `XCTest` to later generate a test report. To fix this, I moved any loading that `KIF` needed from a `+(void)load` method, into `+[KIFTestCase setUp]`. This fixed the issue, and now all of our important `XCTest` logging is back.
Things I tried that didn't work:
1. Doing the setup in `+[XCTestObservationCenter initialize]` (not a good idea for other reasons, but I tried anyway)
2. Doing the setup …

Fixed XCTest load order issues exposed in Xcode 7.3

---

README.md

Deprecation warnings were showing after upgrade to Xcode 7.3:
As such, replaced `__LINE__` with `#line` and `__FILE__` with `#file`.

Updated README for compatibility with Xcode 7.3

---

Additions/UIView-KIFAdditions.m

Currently, when scrolling to an offscreen collection view element that has not yet been created, KIF calls `scrollToItemAtIndexPath:atScrollPosition:` with position `UICollectionViewScrollPositionNone`.  According to [Apple's documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UICollectionView_class/#//apple_ref/doc/uid/TP40012177-CH1-SW60), `UICollectionViewScrollPositionNone` means "Do not scroll the item into view", and indeed what actually happens in my project is that the collection view scrolls to the top and doesn't show the view.  This leads to an endless loop in `accessibilityElementMatchingBlock:`.
None of the other `UICollectionViewScrollPosition` constants are really suitable, so instead I get the element's frame from the collection view's …

Use scrollRectToVisible instead of scrollToItemAtIndexPath

---

Additions/UIAccessibilityElement-KIFAdditions.m
Additions/UIView-KIFAdditions.m
Classes/KIFUITestActor.m

At PSPDFKit our UI tests start to get to a size where waiting for the KIF tests becomes impractical, so we investigated ways to make them run faster.
We had great success with increasing the layer speed on the key window:
```
UIApplication.sharedApplication.keyWindow.layer.speed = speed;
```
This might cause trouble for (very unusual) multi-window setups, but it's still entirely optional to use.
The default value here is 1, so no timeouts are changed by default.
Are there any other important spots where we should divide based on layer speed?

Speed up wait time if layer speed is increased

---

Classes/KIFTestActor.h
Classes/KIFTestCase.m
KIF Tests/AccessibilityIdentifierTests.m

Ran into a problem where we created a KIFTestActor without a line or file, and then when it ran into a test failure it would try and insert a `nil` for `self.file` into the exception user info in NSException+KIFAdditions and crash.
Elected to change KIFTestActor to simply not allow the user to create a KIFTestActor without a file path in the first place (this also works really well with Swift). 
An alternative solution is to perform a nil check before creating the dictionary in the NSException category.

Mark -[KIFTestActor init] unavailable.

---

Additions/UIAccessibilityElement-KIFAdditions.m
Additions/UIApplication-KIFAdditions.h
Additions/UIApplication-KIFAdditions.m
Additions/UIScrollView-KIFAdditions.m
Additions/UIView-KIFAdditions.m
Classes/KIFTestActor.h
Classes/KIFTestActor.m
Classes/KIFTypist.m
Classes/KIFUITestActor.m
Classes/UIAutomationHelper.m
Test Host/AppDelegate.m

This builds on #840 and adds a more central way to scale animation wait times relative to animation speed.
- created `waitForTimeInterval:relativeToAnimationSpeed:` to make it explicit when times are scaled.
- created `KIFRunLoopRunInModeRelativeToAnimationSpeed` to do the same for `CFRunLoopRunInMode`
- added an `animationSpeed` property to UIApplication to simplify getting and setting the keyWindow animation speed (and add some safety to prevent divide by 0 errors)
All tests pass locally with the animation speed set to 100.  I left in the commented code I used to run the tests with fast animations for others to verify.  Ideally, I'd prefer to have a way to run the tests on Travis at fast animation speeds in addition to normal speed.  I'm open to suggestions for how best to implement …

Additional speedups relative to animation speed

---

KIFFramework/KIF.h

This is to allow use of KIFAccessibilityEnabler in other testing frameworks/or when not using KIFTestCase.

Added KIFAccessibilityEnabler.h to KIFFramework

---

Additions/CAAnimation+KIFAdditions.h
Additions/CAAnimation+KIFAdditions.m
Additions/CALayer-KIFAdditions.m
Classes/KIFTestActor.h
Classes/KIFTestActor.m
Classes/KIFUITestActor.h
Classes/KIFUITestActor.m

Animation timeout improvements:
* Expose out a `waitForAnimationsToFinish` method variant to control how long we sleep before starting to look for animations
* Rather than taking the existence of an animation key as being sufficient knowledge of if it is complete, instead calculate when the animation should be completed and compare that against the current time.

Animation timeout improvements

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m

Allows the consumers to specify which part of the cell they want to scroll to - Top/Middle/Bottom.
Middle remains to be the default.

Add "atPosition:" variations to UITableView waitForCellAtIndexPath methods

---

Additions/UIAccessibilityElement-KIFAdditions.m
Additions/UIView-KIFAdditions.h
Additions/UIView-KIFAdditions.m

In our tests, we had a step which tapped a cell in a collection view, identified by its accessibility label.  When the test ran, the collection view was initially offscreen, and while it was being scrolled onto the screen the collection view decided to recycle its cells.  KIF had kept a reference to the original cell which it then used to send the tap event.  As a result, the wrong cell in the collection view was tapped, and the test failed.
This PR addresses the problem by re-checking the accessibility element after calling the method which can cause scrolling.  <s>The logic for identifying accessibility elements which was in the view category has been moved into the accessibility element category so that it can be used in both places.</s>

Fix for cell reuse causing wrong elements to be tapped

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
KIF Tests/TableViewTests.m

These APIs are useful to know when it's safe to perform delete operations when swiping left on table view cells in the edit mode.

Added waitForDeleteStateForCell* methods to reliably wait for cell delete state changes

---

Additions/UIView-KIFAdditions.m

Fixes https://github.com/kif-framework/KIF/issues/802

avoid crash when getting accessibility labels of MKMapView subviews

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
Classes/KIFUIViewTestActor.h
Classes/KIFUIViewTestActor.m
IdentifierTests/KIFUITestActor-IdentifierTests.h
IdentifierTests/KIFUITestActor-IdentifierTests.m
KIF Tests/AccessibilityIdentifierTests.m
KIF Tests/TypingTests.m
KIF Tests/TypingTests_ViewTestActor.m

There are cases where text should be entered without typing simulation.
For example, cases where text is pasted, or where we do repeated text field inputs and want to have more performant tests.
This API sets the text explicitly on the view, without going through the Typist.
Note- this replaces https://github.com/kif-framework/KIF/pull/863

Added "setText:..." helper functions

---

Classes/KIFTypist.h
Classes/KIFTypist.m
Classes/KIFUITestActor.m

I've found in our project when attempting to bump to the latest KIF that sometimes attempting to tap a button directly after typing to be randomly unreliable (tap doesn't actually get invoked). I'm having a hard time reproducing this locally, but it happens on our CI machines (dual core mac minis) often enough to be nearly unusable (every 2-3 runs has a failure).
Rather than using `KIFRunLoopRunInModeRelativeToAnimationSpeed` for modifying the typing delay, I believe test authors should explicitly set `KIFTypist.keystrokeDelay`. The `keyWindow`'s layer animation speed has nothing to do with the keyboard window animations.  However, lowering this value hits the reliability issues I mentioned before. Rather than waiting the .01s between every tap, instead only wait the full .01s after the …

Don't change the typing delay based on animation speed

---

Classes/KIFAccessibilityEnabler.m

This addresses #876 based on what Google is doing in EarlGrey.
https://github.com/google/EarlGrey/pull/148/files
We now use this branch internally at PSPDFKit and Jenkins is green fron 8.4 to 10.0b1. (well, iOS 10 has some troubles but they are not KIF related...)
We no longer show the accessibility inspector, but I actually feel that's a good thing, and it's gone in iOS 10 anyway. The old logic has to remain until KIF drops support for iOS 8.

iOS 10: Use alternate way to enable accessibility

---

Classes/KIFAccessibilityEnabler.h
Classes/KIFAccessibilityEnabler.m
Classes/KIFTestCase.m

The changes after #877 helped with Xcode 8 but broke our Xcode 7 builds. That PR referenced google/EarlGrey#148 but wound up using a different solution than what made it into KIF. This uses a similar approach to the EarlGrey solution.
`libAccessibility.dylib` and  `_AXSSetAutomationEnabled` seem to go way back so this feels relatively safe to use. I wasn't able to test in Xcode 6 locally, but hopefully the tests will pass.
All of our KIF tests pass with this change, using both Xcode 7 and Xcode 8.
@phatmann @steipete (cc: @justinseanmartin re: #880)
---
**UPDATE**: 
There seems to be a lot of flakiness unrelated to the Xcode 7 / 8 changes. I can get this to pass all tests locally every time, but CI seems to fail a lot more often. The pull-to-refresh tests seem to fail pretty reliably on …

Fix Accessibility

---

Classes/KIFUITestActor.m
Classes/KIFUIViewTestActor.h
Classes/KIFUIViewTestActor.m
KIF Tests/MultiFingerTests.m
KIF Tests/MultiFingerTests_ViewTestActor.m
KIF Tests/TableViewTests.m
KIF Tests/TableViewTests_ViewTestActor.m

After running the test cases locally on both hardware and sim
it was noticed that some tests needed a bit more waiting to run
reliably. Perhaps running too fast on robust platform?
Notably:
Tests that type into input fields:
* In "(void)expectView:(UIView *)view toContainText:(NSString *)expectedResult"
the timeout was set to 1.0. This bumps it up to 2.0. Seems to stabilize field tests.
The community will also benefit from this change.
* Predictive text was getting in the way of typing the string, "Test-Driven Development".
The text was getting auto-corrected.  This PR changes it to "Testing"
Tests that utilize gestures:
* MultiFinger and TableView Tests benefit from waitFor... method calls.

Update Test cases for [hopefully] better travis results

---

Test Host/Test Host-Info.plist

Test Host's plist was missing `NSPhotoLibraryUsageDescription` privacy string, which crashes the app on iOS10 when photo library permission is requested.
From [Apple's doc](https://developer.apple.com/library/prerelease/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW17):
> Important: To protect user privacy, an iOS app linked on or after iOS 10.0, and which accesses the user’s photo library, must statically declare the intent to do so. Include the NSPhotoLibraryUsageDescription key in your app’s Info.plist file and provide a purpose string for this key. If your app attempts to access the user’s photo library without a corresponding purpose string, your app exits.

Add NSPhotoLibraryUsageDescription for system alert tests

---

KIF.xcodeproj/project.pbxproj

This header was added to KIF.h in the framework target, but not made public, causing a lot of "non-modular includes" errors if you use the KIF module from Swift.

Make KIFAccessibilityEnabler.h public

---

Classes/KIFAccessibilityEnabler.m

No reason to pass nil in. In fact, for nullability we get an error w/ this at Uber.

Fix passing nil into a method that has an alternative with 1 fewer arguments

---

Additions/UIView-KIFAdditions.m

We ran into a recent test failure within KIF that was fun and convoluted:
1. We're looking for an element on the screen to tap
2. We find a UITableView that is in a UINavigationTransitionView (animating it into place)
3. We find the UIView we want to tap inside the UITableView, but it isn't tappable at its current location, so we try to scroll it into view
4. After scrolling, we sleep for a half second and check to see if it is now tappable
5. After that half second, the UINavigationTransitionView is no longer part of the window (because the animation transition completed)
6. From this point on, we'll recursively attempt to scroll the element into view, wait half a second, and then check to see if it is visible again
It sits recursing infinitely in this loop with a half second sleep …

Fix for really slow stack overflow when tableview is removed from view

---

README.md

In the readme, it shows `import KIF` in your swift test case file, but that fails, and the examples in the `Documentation/Examples` folder doesn't `import KIF`, so it seems wrong.

Fix swift example

---

Additions/UIAccessibilityElement-KIFAdditions.m

Minor logging improvement that has been helping us troubleshoot errors.

Include element and view in 'is not tappable' error details

---

Classes/KIFUITestActor.h
Classes/KIFUIViewTestActor.h

Fix typo: duplicate word doesn't

Fix typo: duplicate word doesn't

---

Classes/KIFUITestActor.m

Currently,
when trying to use `selectDatePickerValue` on DatePickers with minimumDate set, selection fails with no error. 
After debugging I realized - since Apple push into the DatePickers a 1000 rows of data, when setting minimum date - for example Today - the default value will be in the middle (row 500).
Now when the `selectDatePickerValue` method is looking for a future date (e.g "Feb 28") it will start in row 0 and find "Feb 28" of 2016. upon selecting that value, the DatePicker View will jump back automatically to minimum value (Today) and will not select the desired date.
This pull-request suggest a fix. 
I am open for changes, feedback, etc.
I tried the most simple approach i could think of:
1) if this is a DatePicker & Minimum Date is not nil 
2) find Minimum value row (by …

Support for selection in DatePickers with Minimum Date value

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
KIF Tests/PickerTests.m
Test Host/PickerController.m
Test Host/en.lproj/MainStoryboard.storyboard

After discussion with @justinseanmartin on my last pull-request #949 
Here is the suggested wider fix with _KIFPickerSearchOrder_
```
typedef NS_ENUM(NSUInteger, KIFPickerSearchOrder) {
KIFPickerSearchBackwardFromEnd = -2,
KIFPickerSearchBackwardFromCurrentValue = -1,
KIFPickerSearchForwardFromCurrentValue = 1,
KIFPickerSearchForwardFromStart = 2,
};
- (void)selectDatePickerValue:(NSArray *)datePickerColumnValues withSearchOrder:(KIFPickerSearchOrder)searchOrder
- (void)selectPickerViewRowWithTitle:(NSString *)title inComponent:(NSInteger)component withSearchOrder:(KIFPickerSearchOrder)searchOrder
```
I had one small problem with AM:PM, and I fixed it with another IF for that specific case. 
Any other creative solutions will be gladly received.

Add date picker search order

---

Classes/KIFTestActor.m

Partially reverts changes introduced in #819.
We bumped KIF to the latest release for the first time in a while and found that some logic test targets (e.g. no app host) that happen to link KIF into them as a dynamic framework fail to dlopen at load time. I isolated it back to this change, and it appears to fix the issue that we were seeing.
Ideally, we'd have a different set of test dependencies for logic tests and app tests, but the project has manually managed dependencies and this used to work and was simpler for them to manage. As this used to work with v3.4.2, it seemed appropriate to fix this and partially restore the previous behavior.
I'm not clear if the change of moving the +load to a UIApplication was necessary or just seemed more correct. @benasher44?
I'm not 100% clear on …

Move load back into KIFTestActor class

---

KIF.podspec

Just noticed this after bumping to 3.5.2.

Ensure that categories with '+' separator are added to public headers

---

Classes/UIAutomationHelper.m

Patch for consistent crash in acknowledgeSystemAlert() if an app alert is displayed. Capital One has been using this patch on a fork for 6 months.

acknowledgeSystemAlert() crash patch

---

Classes/KIFTestActor.h
Classes/KIFTestActor.m
Classes/KIFUIViewTestActor.h
Classes/KIFUIViewTestActor.m
Documentation/Examples/Calculator/Calculator.xcodeproj/project.pbxproj
KIF Tests/GestureTests_ViewTestActor.m
KIF Tests/ModalViewTests_ViewTestActor.m
KIF Tests/SearchFieldTests_ViewTestActor.m
KIF Tests/TypingTests_ViewTestActor.m
KIF Tests/WaitForTappableViewTests_ViewTestActor.m
KIF Tests/WebViewTests_ViewTestActor.m

I found some actions that existed in `KIFUITestActor` that weren't being exposed in `KIFUIViewTestActor`. This tries to bring it to parity. The typing into first responder I solved by introducing `usingFirstResponder` as a matcher.

Expand the set of exposed UIViewTester matchers and actions

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m

We've deprecated all usage of `tester` and would like to prevent further usages from creeping in.
In order to use it, we are setting: `OTHER_CFLAGS = "$(inherited) -DDEPRECATE_KIF_TESTER=1"`
When that CFLAG is present, it will generate a deprecation warning with the message:
> Use of `tester` has been deprecated; Use `viewTester` instead.

Add an optional compiler flag DEPRECATE_KIF_TESTER

---

Classes/KIFUIViewTestActor.m

Add a safety check that prevents using expectedResult without validating the entered text. This was suggested by @RoyalPineapple in code review.

Prevent using expectedResult without validating the entered text

---

Classes/KIFUIViewTestActor.h

In an effort to decouple element matchers from actions, calls to `[viewTester clearTextFromFirstResponder]` is being deprecated and should be replaced with calls to `[[viewTester usingFirstResponder] clearText]`.

Deprecate 'clearTextFromFirstResponder', as it is now redundant

---

.travis.yml

See if I can get the Xcode 6 Travis machines out of their currently broken state (due to stringio missing in the installed version of rubygems).

Try to fix CI on Xcode 6 Travis machines

---

Additions/UIScreen+KIFAdditions.m
KIF Tests/Additions/UIScreen+KIFAdditionsTests.m

On iOS 11, when performing a "full swipe" on a TableView cell, the first action is performed by default.
The `majorSwipeDisplacement` is currently used for the amount of displacement perform when swiping a cell and it seems that 0.625 is too much and performs the first action automatically. This is breaking our tests as the action is performed so there is no action to tap anymore.
This PR lowers this constant to 0.5, which I would say it's still a major swipe displacement and does not seem to trigger the new behavior on iOS 11 which would be the expected thing IMO.
Maybe in an additional PR we should also expose a method to perform a full swipe so users are also be able to test this new behavior.

Make majorSwipeDisplacement smaller

---

Additions/UIApplication-KIFAdditions.m

The if clause does not check for `directoryCreationError` which is used for `NSFileManager` to create the directory.

Handling the correct error

---

Additions/UIAccessibilityElement-KIFAdditions.m
KIF Tests/TableViewTests.m
KIF Tests/TableViewTests_ViewTestActor.m

On Xcode 9 & iOS 11, `waitForViewWithAccessibilityLabel: @"label text on the cell"` returns its `UITableView`. As commented in the existing code, UITableView is too far in view hierarchy to work with cells level.
On iOS 10, it correctly returns `UITableViewCell` or `UITableViewLabel`.
This PR adds testcases to reproduce issue. (After my some inspections, `tapViewWithAccessibilityLabel` change some unknown states which affects reproducibility, I have added 2 testcases.)
Then this patches the view finding logic by searching `-tableViewCell` in addition to `-view`.
`element accessibilityContainer` for table cells is like below:
iOS 10: `UITextAccessibilityElement -> accessibilityContainer = UITableViewCell`
iOS 11: `UITextAccessibilityElement -> accessibilityContainer = …

Fix waitForView cannot find UITableViewCell or label, and results in UITableView on iOS 11

---

Classes/KIFUITestActor.m

Add an autoreleasepool to prevent object lifetimes from being extended. Thanks @justinseanmartin!

Add missing autoreleasepool

---

KIF.podspec

XCTest does not support bitcode. This causes a build failure when running on a device.

Disable bitcode in podspec

---

README.md

Add documentation to call KIFEnableAccessibility in setUp when not inheriting KIFTestCase. Following up on #889 since I ran into the same issue.

Add documentation to call KIFEnableAccessibility in setUp

---

Classes/KIFUIViewTestActor.h
Classes/KIFUIViewTestActor.m
KIF Tests/TappingTests_ViewTestActor.m
Test Host/en.lproj/MainStoryboard.storyboard

This allows us to differentiate between views that may have the same accessibility label and share some— but not all— accessibility traits.
For example, this allows us to differentiate between a "Next" button in a navigation bar or input accessory (with the ax trait of `.Button`), and a return key that also says "Next" on the input view itself (that may have the ax trait of `.Button` on some OS's \*cough\*iOS 10.2\*cough\* and will always have the ax trait of `.KeyboardKey`).

Add -[KIFUIViewTestActor usingAbsenceOfTraits:] 

---

Classes/KIFUITestActor-ConditionalTests.m
Classes/KIFUITestActor.m

Adds `__autoreleasing` variable qualifier preventing Xcode 9 to raise warnings.
Developers: @stefanlage, @ecaselles
It closes #1034

Fix Xcode 9 warnings

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
Classes/UIAutomationHelper.h
Classes/UIAutomationHelper.m

- method for tapping system alerts at varying index. This is incredibly useful for tapping system alert (like location alerts) that use new iOS 11 permissions (never allow, allow while in app, always allow - as they pertain to location permissions in this instance).
- refactored `acknowledgeSystemAlert` to call `acknowledgeSystemAlertWithIndex:`
Inspired by: https://github.com/jamesjn/KIF/blob/3361a50389309326aa4a4fc580d4a37421829b58/Classes/UIAutomationHelper.m#L131 (@jamesjn)

Add more generic alert tapping capabilities

---

.travis.yml
KIF Tests/ModalViewTests.m
KIF Tests/ModalViewTests_ViewTestActor.m
Test Host/TapViewController.m

Add a CI config for Xcode 8 w/ iOS 10. This requires fixing some tests that break on this configuration.
The second commit ("Disable autocorrect when entering text") is an attempt at handling a longstanding issue where controls that have autocorrect enabled on them can lead to unexpected things entered. This is causing a new test failure in the new CI configuration of changing `ll` to `lol`.
I don't see a reason why a test would want to rely on the OS level autocorrect functionality in their test. Please feel free to voice concern about this, looking for opinions. The reasonable (and up-to-now expected) alternative would be to modify the particular text field in the Test App to not have autocorrect enabled.
I still need to do some more testing on this however, as the fix doesn't seem to …

Add a CI config for Xcode 8 w/ iOS 10

---

.travis.yml
Additions/UIAccessibilityElement-KIFAdditions.m
Additions/UITableView-KIFAdditions.m
Additions/UIView-KIFAdditions.h
Additions/UIView-KIFAdditions.m
Classes/UIAutomationHelper.m
KIF Tests/ExistTests.m
KIF Tests/ExistTests_ViewTestActor.m
KIF Tests/ModalViewTests.m
KIF Tests/ModalViewTests_ViewTestActor.m
KIF Tests/SpecificControlTests.m
KIF Tests/SpecificControlTests_ViewTestActor.m
KIF Tests/WaitForAnimationTests.m
KIF Tests/WaitForAnimationTests_ViewTestActor.m
KIF Tests/WaitForViewTests.m
KIF Tests/WaitForViewTests_ViewTestActor.m
KIF.xcodeproj/xcshareddata/xcschemes/KIF.xcscheme
README.md

Resolves #1000, #1022
As a followup to getting CI running on Xcode 8, now we are getting a configuration running against Xcode 9. 
After getting Travis to run the tests properly on XC6, it turns out that they fail anyway. I don't have an environment that I can run the tests and fix them, and it seems like it is time to drop Xcode 6 support anyway (XC7 was GMed 2.5 ago). It would probably honestly be reasonable to even drop XC7 support as well, but we might as well keep it as long as the tests are passing and it isn't causing us trouble.
KIF Framework Changes:
* Changed `[UIAccessibilityElement-KIFAdditions viewContainingAccessibilityElement:tappable:error:]` to only attempt to scroll an element into the view if it isn't currently visible. There was some behavior broken in the "swipe to …

Xcode 9 and iOS 11 fixes + Travis CI (& drop XC6 support)

---

Additions/UIAccessibilityElement-KIFAdditions.m
Additions/UIView-KIFAdditions.m
Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
KIF Tests/CollectionViewTests.m
KIF Tests/ScrollViewTests.m
KIF Tests/TableViewTests.m

The `KIFUITestActor` by default, performs actions with animation. Those animations (scrolling a table view or a scroll view) can't be speeded up using the `layer.speed` and in a test suite with hundred of tests involving UITableViews this could slow down dramatically the overall running time. 
This PR creates a new settable property in the `KIFUITestActor` to allow disabling this default behaviour.

Allow disabling UITestActor animations to speed up tests

---

Classes/KIFTextInputTraitsOverrides.m
KIF.podspec

The original change to prevent autocorrect/smart quotes/smart dashes only worked on `UITextField`, but not `UITextView`. This simply adds that change for `UITextView` as well.

Adding autocorrect/smart quotes/smart dashes swizzling for UITextView

---

Classes/KIFTestActor.h
Classes/KIFTestActor.m
Classes/KIFUITestActor.m

We've found that a race condition can sometimes occur whereby a touch event enqueued on the main queue runloop executes before the UI element it's meant to tap has actually appeared onscreen.
When that happens, KIF can wind up sending UI tap events to a view while it's still in the midst of animating onscreen.
We've determined that enqueuing a simple task (set a boolean to `YES`) on the main thread, and spinning a runloop until its execution just before the end of `waitForAnimationsToFinishWithTimeout`, we can avoid this race condition.
Users can configure how long we wait (or if we wait at all, if set to 0) by setting `KIFTestActor.mainThreadDispatchStabilizationTimeout`, or pass a custom timeout to `[KIFUITestActor waitForAnimationsToFinishWithTimeout:(NSTimeInterval)timeout …

Adding stabilization code to waitForAnimationsToFinishWithTimeout

---

.travis.yml

Justification is based off of a comment in another PR by: @qzim, "https://data.apteligent.com/ios/ indicates a 0.46% iOS 8 usage"

Remove travis tests for iOS 8.1 and replace with iPad 5th gen

---

Classes/KIFTestActor.m
Classes/KIFTestCase.m

There isn't a need to require test writers to explicitly call
KIFEnableAccessibility. Instead, call to enable accessibility on
the first attempt to perform an action via KIFTestActor.
This resolves issue #1085.

Issue #1085: Make XCTestCase 'just work'

---

Additions/XCTestCase-KIFAdditions.m

Something broke in this code starting with Xcode 10. For now, this will be disabled and can be fixed later by anyone that relies on this functionality.
Resolves #1084
CC: @maryamaffinityclick (added this functionality)
CC: @LWX124 (reported the issue)

Issue #1084: Avoid `XCUIScreenshot` in Xcode 10 Beta, where the functionality is broken

---

.travis.yml
Additions/UIScrollView-KIFAdditions.m
Test Host/ScrollViewController.m
scripts/ci.sh

When `UIScrollView` has some `contentInset` set, the `scrollViewToVisible:animated:` is not scrolling to the right position. This PR exposes the bug in the tests and fixes the implementation.

Fix scrollViewToVisible:animated:

---

Additions/XCTestCase-KIFAdditions.m

In a project of ours that uses KIF, we were receiving a warning for usage of XCUIScreen on [this line](https://github.com/kif-framework/KIF/blob/master/Additions/XCTestCase-KIFAdditions.m#L78).
I've resolved this by adding an `@available` check.

Fix warning of XCUIScreen availability

---

Additions/UIApplication-KIFAdditions.m

The issue is pretty self explanatory. We were using this helper in our code and ran into a situation where keyWindow may be nil if this helper is used during test setup.

Don't crash if there is no key window

---

Additions/UIAccessibilityElement-KIFAdditions.m

It prevents partially offscreen UITableViewCell elements from being made visible. I don't think this clause is necessary with an iOS 8+ minimum supported version we have now for KIF.

Remove check preventing scroll UITableViewCells

---

Additions/UIView-KIFAdditions.m

When attempting to tap offscreen table elements, after `[tableView scrollToRowAtIndexPath:indexPath atScrollPosition:UITableViewScrollPositionNone animated:animationEnabled]` is called, the scrolling never actually occurs before the call to `[tableView cellForRowAtIndexPath:indexPath]`, which will always return `nil` for offscreen table cells. A yield could be inserted in there, but for large tables, that would be an enormous amount of time.
The spinning of the runloop after that block only allows the final call to `scrollToRowAtIndexPath` to be executed, so the code will only succeed if the cell is in view initially, or it's in the final scrolled section in the table. This code, as it was, would never succeed if the cell being sought was above the initially scrolled area of the table. …

Fixing broken table scrolling

---

Additions/UIView-KIFAdditions.m

When tapping a `UICollectionView`, sometimes the data in the cell might change prior to being displayed, since we're only pulling it from the data source. So here we simulate the cell appearing onscreen.

Fixing UICollectionView cell tapping

---

Classes/KIFUITestActor.m

When an UIPopover is presented in an animated fashion when an element is tapped, that element may not become first responder until after the animation is completed. This change gives waits for the animation to complete before checking that it became first responder. 
Moving the `waitForAnimationsToFinish` introduced some other test failures when the element that became first responder is moved offscreen. For this reason, the additional check of `![view isProbablyTappable]` was added.

Fix issue with elements not becoming first responder fast enough

---

Classes/KIFSystemTestActor.m

Fixes:
```
KIF/Classes/KIFSystemTestActor.m:61:64: error: implicit conversion loses integer precision: 'UIDeviceOrientation' (aka 'enum UIDeviceOrientation') to 'int' [-Werror,-Wshorten-64-to-32]
[[UIDevice currentDevice] setValue:[NSNumber numberWithInt:orientation] forKey:@"orientation"];
```

Fix Xcode 11 (Beta) build error (implicit conversion warning)

---

Additions/UIApplication-KIFAdditions.m

If writing a screenshot fails due to failure to create a directory, an error is assigned to the `error` parameter. However, when `writeScreenShotForLine:...` is called with a `NULL` error param by `writeScreenshotForException:` in XCTestCase-KIFAdditions.m, the assignment causes a crash with EXC_BAD_ACCESS.
Relevant excerpt from XCTestCase-KIFAdditions.m: https://github.com/kif-framework/KIF/blob/0ea470b4731c95782d9a34342efbf5de3ec23183/Additions/XCTestCase-KIFAdditions.m#L67 
This regression was introduced by commit f4705fb963dd872995580846eaa777681c10fd1a (#981), which changed the error checked by the `if (error) { ... }` check away from `error`. 
Revert f4705fb963dd872995580846eaa777681c10fd1a -- check proper error again.
This parallels all the other `if (error)` checks in …

Prevent EXC_BAD_ACCESS crash by null-checking proper error

---

Classes/UIAutomationHelper.m

We need to dig through the hierarchy manually rather than asking for the application's alert
Fixes #1125

Fixed acknowledgeSystemAlert on iOS 13.1

---

Classes/UIAutomationHelper.m

After upgrading to Xcode 11.1, KIF tests on our app were no longer able to acknowledge system notifications. After debugging it was found that the UIAlert is not always the first item in the list of elements. This change searches the list of elements for the UIAlertControllerView making it more resilient.
May help issue #1127

Fix bug when acknowledging system alerts in Xcode 11.1

---

Classes/KIFUITestActor.m

Previously we would call `UITableView.scrollToRow(at:at:animated:)`
every runloop while we waited for the scroll to complete. This caused
multiple unnecessary calls to the delegate's
`scrollViewDidEndScrollingAnimation(_:)` method. This change resolves
the issue by moving the call to scroll to the row outside of the
`KIFTestActor.run(_:)` block.

Scroll once when waiting for UITableViewCells

---

Additions/UIApplication-KIFAdditions.h
Additions/UIApplication-KIFAdditions.m
Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
Classes/KIFUIViewTestActor.h
Classes/KIFUIViewTestActor.m
IdentifierTests/KIFUITestActor-IdentifierTests.m

Previously searches for `UIWindow.firstResponder` were limited to the
`UIApplication.keyWindow`. In practice, it is very possible for users to
add additional valid windows that are not the key window and have first
responders. To accommodate those cases, this change broadens the search
for a first responder of an application to an array of first responders
found in `UIApplication.windowsWithKeyWindow`.

Widen `firstResponder` searches to all windows

---

Additions/UITouch-KIFAdditions.m

Fixes Issue #1153 
This uses @steipete's fix for iOS 14 crashing outlined [here](https://github.com/google/EarlGrey/issues/1357#issuecomment-648921968).
I've tested using iOS 14 and earlier iOS versions to make sure this works as intended. 
I am currently following the thread [here](https://github.com/google/EarlGrey/issues/1357)  to see if any new information pops up around this and will be investigating this more in the future to see if there is a better longterm solution, however to get folks unblocked this should work for now.

Issue #1153: Fix crash in _setIsFirstTouchInView and setIsTap for iOS 14

---

Additions/UIView-KIFAdditions.m

For more recent iOS versions the internal view hierarchy of navigation bar buttons has changed. A lot of unit tests are broken because it is not possible to tap on the back button anymore.
This PR adds a check for marking the new button as a navigation item view.

Fix navigation back button tap (issue #1134)

---

Additions/UIView-Debugging.m

Fixes issue #1146 where date pickers print over 12k lines of text.
Creates a smaller description of the date picker and doesn't print all of its subviews

Fixes issue #1146 where date pickers print over 12k lines of text

---

Additions/CALayer-KIFAdditions.m

To avoid changing layers and running into `Collection CALayerArray was mutated while being enumerated`

Copy sublayers for iterating

---

Classes/KIFUITestActor.m

Previously the
`waitForAccessibilityElement:view:withLabel:value:traits:fromRootView:tappable:`
method checked only once for the presence of the element and immediately
failed if it was not present without waiting as the name would suggest.

Fix waiting for an accessibility label from a root view

---

.github/workflows/build.yml
.travis.yml
Classes/KIFUITestActor.m
Classes/UIAutomationHelper.m
KIF Tests/AccessibilityIdentifierTests.m
KIF Tests/AccessibilityIdentifierTests_ViewTestActor.m
KIF Tests/AutocorrectTests.m
KIF Tests/AutocorrectTests_ViewTestActor.m
KIF Tests/BackgroundTests.m
KIF Tests/GestureTests.m
KIF Tests/GestureTests_ViewTestActor.m
KIF Tests/LandscapeTests.m
KIF Tests/LandscapeTests_ViewTestActor.m
KIF Tests/LongPressTests.m
KIF Tests/LongPressTests_ViewTestActor.m
KIF Tests/SystemAlertTests.m
KIF Tests/TableViewTests.m
KIF Tests/TableViewTests_ViewTestActor.m
KIF.podspec
README.md
Test Host/TestSuiteViewController.m

* Move newer iOS 12 versions to use GitHub actions. 
* GitHub actions are faster and they support archiving artifacts without having to host them somewhere
*  All future iOS versions should use GitHub actions
* Once iOS 11 is deprecated we will move completely off of travis CI
* iOS 11 is not supported on github actions so we are keeping iOS 11 on travis.
* Officially only support only iOS 11+
* Various fixes in tests for new iOS version
* Disable tests on known bugs in iOS versions
* i.e. tapping status bar in ios12+
* Datepicker selection fix
* Update where we select the when reactivating the app, this may break in pre-ios11

Add CI configuration for iOS 12

---

Additions/UIApplication-KIFAdditions.h
Additions/UIApplication-KIFAdditions.m
Additions/UITableView-KIFAdditions.m
Additions/UIView-KIFAdditions.m
KIF.xcodeproj/project.pbxproj
KIF.xcodeproj/xcshareddata/xcschemes/KIF.xcscheme
Visualizer/KIFEventVisualizer.h
Visualizer/KIFEventVisualizer.m
Visualizer/KIFTouchVisualizerView.h
Visualizer/KIFTouchVisualizerView.m
Visualizer/KIFTouchVisualizerViewCoordinator.h
Visualizer/KIFTouchVisualizerViewCoordinator.m

Adds a touch visualizer to see where touches are being sent to. Currently it has a default look and feel. We can have a configuration object that can get set if we feel in the future we want customizability over the visualization of touches.
This is an explicit opt-in feature similar to printing the view hierarchy.

Adds a visualizer to KIF

---

Classes/KIFUITestActor.m

`UIDimmingView` looks to be replaced with `_UITouchFallbackView` in iOS 14. This PR allows us to fallback to `_UITouchFallbackView` when `UIDImmingView` isn't found.

Fix Issue #1181 - `dismissPopover` does not work on iOS 14

---

KIF.podspec

It wasn't added when it originally was put into the codebase. 
I'll be updating the project to catch this in CI

Add Visualizer to podspec

---

Additions/UIView-Debugging.m
Visualizer/KIFEventVisualizer.h
Visualizer/KIFEventVisualizer.m

Also add event visualizer to be above input views.
Input views are at 1000001 and if you set a window level higher than 1000000 it will still max out at `1000000`. So override the window level to always return higher than that.
Made it higher than `1000002` just incase there are other windows

Exclude KIFEventVisualizer from printing hierarchy

---

Sources/KIF/CALayer-KIFAdditions.m

This speeds up tests running to not the waitForAnimations timeout when a textfield cursor is on screen

Exclude UITextSelectionViewCaretBlinkAnimation from hasAnimations check

---

Sources/KIF/Additions/XCTestCase-KIFAdditions.m

We only officially support Xcode 11+ so we can update re-add xcattachment screenshots everywhere

Readd xcattachment screenshots

---

Sources/KIF/Classes/KIFTypist.m

Making sure that the keyboard "flushes" on each keystroke to account for slower devices/simulators that may take longer to run or if a device is doing a lot of other processes and is slowing down the machine the keystroke will still get processed before "moving on" with the test, possibly causing errors within the test.

Wait for keyboard input tasks to finish before continuing typing

---

Sources/KIF/Classes/KIFTestActor.h
Sources/KIF/Classes/KIFTestActor.m
Sources/KIF/Classes/KIFUITestActor.m

Have a settable timeout to allow users to increase it to account for slower devices/simulators that may take longer to run or if a device is doing a lot of other processes and is slowing down the machine.

Add first responder timeout

---

KIF Tests/PickerTests.m
Sources/KIF/Classes/KIFUITestActor.m
Test Host/Base.lproj/MainStoryboard.storyboard
Test Host/PickerController.m

The NSDateComponents object which is used to select the date picker values needs to reflect the timeZone set on the datePicker to properly select the values.
Fixes https://github.com/kif-framework/KIF/issues/1214

Sets the timezone when selecting a date picker value

---

Sources/KIF/Additions/UIView-KIFAdditions.m

Old implementation does not restore the initial offset in the table view after a view search

Fixed table view scroll behavior

---

Sources/KIF/Additions/UITouch-KIFAdditions.m

Hi there!
This is a fix for this issue I've created [here](https://github.com/kif-framework/KIF/issues/1233)

Removed setIsTap to avoid unrecognized selector sent to instance issue on iOS 15

---

.github/workflows/build.yml
Sources/KIF/Additions/UIAccessibilityElement-KIFAdditions.m
Test Host/TableViewController.m

`UIAccessibilityElementMockView` does not respond to the selector `view` anymore, which causes the tableview to be returned when looking for a subview in the hierarchy.  
This checks the class name to see if it's a `UIAccessibilityElementMockView` then will get the view via `valueForKey:`
Fixes #1240

Fix #1240 waitForView on label in tableview not working

---

KIF.podspec
Sources/KIF/Additions/XCTestCase-KIFAdditions.m

XCUI is more locked down with the latest release of Xcode 13 + iOS 15. with this latest release we cannot do certain actions from XCUI including screenshots. 
This changes our use XCUI to take screenshots on failures to manually snapshotting the main screen on failures.

Remove use of XCUI for taking screenshots

---

Sources/KIF/Additions/UIView-KIFAdditions.m

`isTappable` checks to see if a view is on screen or tappable by the user. If a view has a gesture recognizer it doesn't make it tappable if it's off screen or hidden by another view. 
This takes out that check as it doesn't accurately represent if a view is actually tappable.
This still passes the tests that were introduced when this check was added so there should be no regression in functionality.

Remove hasTapGestureRecognizer

---

Sources/KIF/Additions/UIView-KIFAdditions.m

This uses scrolling to positions to find elements in the collectionview rather than using the datasource directly to get the cell.

Mimic the logic to find elements in UITableView to UICollectionview

---

Sources/KIF/Additions/UIAccessibilityElement-KIFAdditions.m

The actual view can be changed due to cell reuse after scrolling. This change ensures that once we scroll we have the same view as before we did so the action being taken is correct

Check that we have the same view after scrolling

---

.github/workflows/build.yml

In github actions it looks like macos-latest has changed to 11. This specifies only Xcode 10 should run on 10.15 and everything else should run on 11

Directly Specify the OS versions and move Xcode 10 to 10.15

---

Sources/KIF/Classes/KIFUITestActor.m

This re-introduces https://github.com/kif-framework/KIF/pull/1070 where elements off screen in a scrollview need to be scrolled before they are tapped.
In iOS 15 some elements in a tableview are within the scrollview though not on screen, specifically table view footers (not to be confused with table view section footers). This causes an element to be matched and "found" but untappable.  Adding this will make sure that we scroll to the element before tapping it

Fix bug with table view elements that are matched but offscreen

---

Sources/KIF/Classes/KIFUITestActor.m

This pull request fixes tapping issue that happens when dealing with SwiftUI views and scroll views in tests.
Before this fix is applied, it's not possible to click on views in SwiftUI view hierarchy that are located outside scrolled bounds. This happens because SwiftUI applies some sort of flattening logic on the resulting view hierarchy, and the actual tappable view is only a small part of a bigger view.
For example, here is a debugger output from `_scrollViewToTappablePointIfNeeded` in a test where this issue happens:
```
(lldb) po view.frame
(origin = (x = 0, y = 0), size = (width = 390, height = 1362))
(lldb) po view
<_TtCC7SwiftUI17HostingScrollView22PlatformGroupContainer: 0x14b549a50; frame = (0 0; 390 1362); layer = <CALayer: 0x600000b4c8a0>>
(lldb) po element …
```

Use accessibility element to find correct tappable point

---

Package.swift

Tiny PR to remove a warning that get generated by consumers of KIF via SPM, which warns out that the supported deployment targets start from >= 9.0.

Fix deployment target

---

KIF Tests/CompositionTests_ViewTestActor.m
Sources/KIF/Classes/KIFUITestActor-ConditionalTests.m
Sources/KIF/Classes/KIFUITestActor.m
Sources/KIF/Classes/KIFUIViewTestActor.m
Sources/KIF/IdentifierTests/KIFUITestActor-IdentifierTests.m

This PR resolves #1260.
I'm not using KIF, but I fixed a similar issue in wix/Detox ([here](https://github.com/wix/Detox/pull/3420)) and one of our issues regarding this error was mentioned by one of your users ([here](https://github.com/kif-framework/KIF/issues/1260)).
I was able to reproduce the error mentioned in #1260 with your tests suite, using Xcode 13.4 and iOS 15.5 Simulator.
After applying the same solution I used for Detox (replacing predicate-with-format with predicate-with-block), all tests were passed.

fix(iOS): fix iOS 15.5 `NSPredicate` error.

---

README.md

Use inline code formatting to prevent interpretation of special characters as formatting syntax

Fix quotes in README

---

.github/workflows/build.yml
Sources/KIF/Additions/UIView-KIFAdditions.m
Sources/KIF/Classes/KIFSystemTestActor.m
Sources/KIF/Classes/KIFUITestActor.m

Fix for iOS 16. 
- Adding the pickerView into the inputView of a textfield is handle different than the other iOS versions. On iOS 16, it is part of the property `_fallbackView` from `_UIRemoteKeyboardPlaceholderView`, but it is not part of the UI hierarchy (I don't know why). So in the parts that checked for elements, I added another validation for the `_UIRemoteKeyboardPlaceholderView`
- UIDatePicker is not a subclass of UIPickerView. And it has doesn't has an UIPickerView as subview. The hierarchy is UIDatePicker -> _UIDatePickerView ->  ... -> UIPickerColumnView ... But it has an _UIPickerView property that works if used.
- `[[UIDevice currentDevice] setValue:@(orientation) forKey:@"orientation"]` doesn't work anymore. We need to use `requestGeometryUpdateWithPreferences` from …

Fix ios 16

---

KIF Tests/GestureTests.m
KIF Tests/GestureTests_ViewTestActor.m
Sources/KIF/Additions/UITouch-KIFAdditions.h
Sources/KIF/Additions/UITouch-KIFAdditions.m
Sources/KIF/Additions/UIView-KIFAdditions.h
Sources/KIF/Additions/UIView-KIFAdditions.m
Sources/KIF/Classes/KIFUITestActor.h
Sources/KIF/Classes/KIFUITestActor.m
Sources/KIF/Classes/KIFUIViewTestActor.h
Sources/KIF/Classes/KIFUIViewTestActor.m
Test Host/Base.lproj/MainStoryboard.storyboard
Test Host/GestureViewController.m

As discussed in issue #1281, I tried to address the problem by adding a new method to the tester. This method simulates a screen edge pan gesture by manually setting the `_edgeType` property. I wonder if there's any better solution, any feedback is greatly appreciated.

Add support for swiping from the specified edge of the screen

---

KIF Tests/AccessibilityIdentifierPullToRefreshTests.m

I was able to reproduce this issue one time on my local machine. There is a small time window where Bingo is no longer present on the screen, but the greeting view has not yet completely finished animating out. When this happens, the tap for the subsequent test `AccessibilityIdentifierTests testClearingAndEnteringTextIntoViewWithAccessibilityLabel` will fail, because it won't have successfully opened the `Tapping` tests screen.

PullToRefreshTests can exit before the greetingView is finished animating out

---

KIF Tests/AccessibilityIdentifierTests.m
KIF Tests/AccessibilityIdentifierTests_ViewTestActor.m
KIF Tests/LongPressTests.m
KIF Tests/LongPressTests_ViewTestActor.m
KIF Tests/TypingTests.m
KIF Tests/TypingTests_ViewTestActor.m

In iOS, the edit menu is designed to display two commands and a "Forward" or "Back" page button when there are more than two commands available.
If the pasteboard already contains a string, the edit menu will show "Paste" and "Select" commands. The "Select All" command can be accessed on the next page.
Executing a case that taps the "Cut" command will result in the failure of all subsequent cases that require tapping the "Select All" command.
One solution to this is to clear the pasteboard before the "Select All" cases.

Fix occasional CI failures on the iPhone simulator

---

Sources/KIF/Additions/UIApplication-KIFAdditions.m

On iOS 17 Simulator, we cannot render a keyboard window and get a fully black screenshot image.
As a workaround, this PR suppress rendering the keyboard window
* call `writeScreenshotForLine` after using a keyboard
* the keyboard window renders black pixels even when the keyboard is hidden on iOS 17 Simulator
iOS 16.4 Simulator does not reproduce the issue, for both builds on Xcode 14.3.1 or Xcode 15.0. It seems to depend on the runtime simulator version.
Either the keyboard window is not rendered, or, it renders the keyboard image over the app window as same as displayed on the Simulator
a fully black screenshot image will be rendered

iOS 17 - fix black screenshots after using a keyboard

---

KIF Tests/CustomActionTests_ViewTestActor.m
KIF.xcodeproj/project.pbxproj
Sources/KIF/Additions/UIAccessibilityCustomAction+KIFAdditions.h
Sources/KIF/Additions/UIAccessibilityCustomAction+KIFAdditions.m
Sources/KIF/Classes/KIFUIViewTestActor.h
Sources/KIF/Classes/KIFUIViewTestActor.m
Test Host/TapViewController.m

Custom actions allow developers to provide custom interactions that can be initiated through assistive technologies like VoiceOver and Switch Control. For example, VoiceOver lets users access actions quickly using the Actions rotor.
Custom actions are relied on heavily by SwiftUI's `.accessibilityElement(children:.combine)`  view modifier. 
This PR introduces two methods on KIFUIViewTestActor to enable validation and activation of an element's custom actions within KIF tests. 
`- (instancetype)usingCustomActionWithName:(NSString *)name;` adds a predicate that searches elements for one that provides a custom action with a specified name. 
`- (void)activateCustomActionWithName:(NSString *)name;` first performs a search for an element that provides a custom action with a specified name and …

Adding support for accessibility custom actions

---

KIF Tests/AccessibilityIdentifierTests.m
KIF Tests/AccessibilityIdentifierTests_ViewTestActor.m
KIF Tests/TappingTests_ViewTestActor.m
Sources/KIF/Additions/UIAccessibilityElement-KIFAdditions.h
Sources/KIF/Additions/UIAccessibilityElement-KIFAdditions.m
Sources/KIF/Additions/UIApplication-KIFAdditions.h
Sources/KIF/Additions/UIApplication-KIFAdditions.m
Sources/KIF/Additions/UIView-KIFAdditions.h
Sources/KIF/Additions/UIView-KIFAdditions.m
Sources/KIF/Classes/KIFUITestActor-ConditionalTests.h
Sources/KIF/Classes/KIFUITestActor-ConditionalTests.m
Sources/KIF/Classes/KIFUITestActor.h
Sources/KIF/Classes/KIFUITestActor.m
Sources/KIF/Classes/KIFUIViewTestActor.h
Sources/KIF/Classes/KIFUIViewTestActor.m
Sources/KIF/IdentifierTests/KIFUITestActor-IdentifierTests.h
Sources/KIF/IdentifierTests/KIFUITestActor-IdentifierTests.m
Test Host/Base.lproj/MainStoryboard.storyboard

This MR introduces the method `tryFindingViewInFrame(withAccessibilityIdentifier: )` that allows to check the visibility of an element **in the current frame** as it is showed to the user, without any additional interaction.
The method usingCurrentFrame() has been added in the new `KIFUIViewTestActor` to maintain parity with `KIFUITestActor`.
In some UITests we want to ensure an element is visible in the **current frame**. 
When the element we want to assert is visible is inside a `scrollView`,`tableView` or `collectionView` the method `tryFindingView(withAccessibilityIdentifier: )` causes a scroll to the offset where the element is placed, making it visible even if it wasn't. This behaviour does not allow to have reliable visibility checks (eg. if an element exists but is not actually …

Introducing tryFindingViewInFrame() to avoid scroll

---

KIF.xcodeproj/project.pbxproj
Sources/KIF/Classes/KIFUIViewTestActor.h
Sources/KIF/Classes/KIFUIViewTestActor.m
TestHost/AccessibilityViewController.m
TestHost/Base.lproj/MainStoryboard.storyboard
TestHost/TapViewController.m
Tests/AccessibilityActivationTests_ViewTestActor.m
Tests/CustomActionTests_ViewTestActor.m

Some of my recent accessibility work in our design system results in accessibility elements that abstract away the interactivity of some underlying controls. These elements subsume the interactivity of their children and re-expose the functionality via `accessibilityActivate()`.
Unfortunately this breaks KIF matching resulting in the need for an escape hatch to allow activation of elements with greater complexity.
performAccessibilityActivateWithExpectedResult calls accessibilityElement() on the found element and compares its result to the expectation.

added performAccessibilityActivateWithExpectedResult

---

Sources/KIF/Additions/CALayer-KIFAdditions.h
Sources/KIF/Additions/CALayer-KIFAdditions.m

We identified 3 issues where calls to `waitForAnimationsToFinish` would wait longer than we'd expect:
1. We're traversing through hidden views, which will sometimes finds animations on elements that aren't visible on the screen.
2. We're ignoring infinitely repeating animations, but not really long animations. In some cases this might be just a huge value that someone made up or it could be a slow animation. In either case, we probably don't want to wait for those to complete implicitly.
3. The `KIFTouchVisualizerView` was added to show where touch events are happening, but they animate in a separate window and have an alpha fade for .75s. Every tap action then will wait for a minimum of .75s after the tap for that animation to complete, which was unintentional. Credit to @amorde for …

Speed up unnecessarily and unintentionally slow `waitForAnimationsToFinish` calls

---

Sources/KIF/Classes/KIFUITestActor.m
TestHost/AccessibilityViewController.m
TestHost/Base.lproj/MainStoryboard.storyboard
Tests/AccessibilityActivationTests_ViewTestActor.m

If a call to `accessibilityActivate()` returns false, VoiceOver (and related assistive technologies) will issue a tap event to the element as a secondary attempt to activate it via the the standard touch pipeline. The `accessibilityActivationPoint` can be set on elements to instruct assistive technologies where specifically on the screen to issue this tap event. 
We should take this property into consideration when deciding the same. This is particularly important when the value is set deliberately. Failing to do so can cause taps to be issued that don't properly activate the element. 
In the case where the property has not been explicitly set. The default value is the midpoint of the accessibility frame, which itself has a default value equivalent to self.frame this makes the change …

Use accessibilityActivationPoint when determining where to tap elements.

---

Sources/KIF/Additions/UIView-KIFAdditions.m

In Xcode 16, an assertion was to UICollectionView:
> Expected dequeued view to be returned to the collection view in preparation for display. When the collection view's data source is asked to provide a view for a given index path, ensure that a single view is dequeued and returned to the collection view. Avoid dequeuing views without a request from the collection view. For retrieving an existing view in the collection view, use -[UICollectionView cellForItemAtIndexPath:] or -[UICollectionView supplementaryViewForElementKind:atIndexPath:]. 
Rather than calling `-[UICollectionViewDataSource collectionView:cellForItemAtIndexPath:]` and `[UICollectionViewDelegate collectionView:willDisplayCell:forItemAtIndexPath:]`, instead we will scroll the collection view's content offset to make the …

Fix UICollectionView cell enumeration hitting asserts in Xcode 16

---

.github/workflows/build.yml
Sources/KIF/Additions/CALayer-KIFAdditions.m
Sources/KIF/Additions/NSObject+KIFSwizzle.m
Sources/KIF/Additions/UIWindow+KIFSwizzle.m
Sources/KIF/Classes/KIFUITestActor.m
Tests/AccessibilityIdentifierTests.m
Tests/AccessibilityIdentifierTests_ViewTestActor.m
Tests/LongPressTests.m
Tests/LongPressTests_ViewTestActor.m
Tests/TypingTests.m
Tests/TypingTests_ViewTestActor.m

Configure KIF CI to run on Xcode 16.0 & iOS 18.0, bringing us to a total of 6 CI configurations. I've moved the one that does the extra validation to the Xcode 16 build part. If I could test iOS 16 w/ Xcode 15, I'd drop support for Xcode 14.3.1, but that isn't set up on GH hosted runners and I think it is worth still testing on iOS 16.
Aside from needing to land the fix for UICollectionView asserts in #1307, `TypingTests testEnteringTextIntoFirstResponder` was also failing on CI and required some behavior changes to get them working reliably. The behavior was that we were attempting to tap "Select All" after a long press, but we weren't waiting long enough for the popover control to appear. Tapping too early was then dismissing the popover rather than actually performing a "Select All" …

Xcode 16 in CI

---

Sources/KIF/Additions/UIView-KIFAdditions.m

I observed multiple tests failing where the collection view did not scroll to the indexPath.
I changed the scrolling to use `scrollToItemAtIndexPath` if it fails to get the cell and it fixed the failing tests.

Fix for collection view scrolling not working in some tests

---

.github/workflows/build.yml

Xcode 14.3.1 is not available on mac os 14 and the build is failing
Example here: https://github.com/kif-framework/KIF/actions/runs/12056785863/job/33620032419?pr=1313

Remove Xcode 14.3.1

---

Sources/KIF/Additions/UIView-KIFAdditions.m

I found many tests that were hitting this assertion.  After trying looping around the run loop and still not finding these cells I'm changing this to just continue if a cell can't be found.

Skip cells that can’t be found

---

.github/workflows/build.yml
Scripts/ci.sh
Sources/KIF/Additions/UIView-KIFAdditions.m

Only use the new scrolling logic when on iOS 18+

Change the collection view changes to iOS 18

---

KIF.podspec
Sources/KIF/Classes/KIFUITestActor.m

The reverted commit increases the duration of waitForAnimationToFinish and slows down KIF tests.
Also bumps the version to 3.11.1.

Revert the change causing KIF performance regression

---

Sources/KIF/Additions/UIView-Debugging.h
Sources/KIF/Additions/UIView-Debugging.m
Sources/KIF/Additions/XCTestCase-KIFAdditions.m

Adds an environment variable `KIF_ATTACHVIEWTREEONFAILURE` which, when set to `YES`, will attach a `View Hierarchy.txt` attachment to the test results.
The contents are the same as the view hierarchy description that gets printed when `KIF_PRINTVIEWTREEONFAILURE` is set.

Add support for adding the view hierarchy description as an attachment

---

Sources/KIF/Additions/CALayer-KIFAdditions.m

Fixes a bug in the logic for determining if a given layer has active animations.
When encountering an animation that has already completed (its completion time is in the past), we incorrectly determined it was _not_ completed. This would lead to `waitForAnimationsToFinish()` to continue running until it hits the animation wait timeout, which defaults to 2 seconds.

Fix a bug when determining whether an existing animation has completed
