Documentation/Examples/Testable Swift/Testable Swift/MasterViewController.swift

Added missing optional chaining.

Fixes compilation error in Swift example project.

---

Classes/KIFUITestActor-ConditionalTests.h

Fix documentation typos

---

Additions/UIApplication-KIFAdditions.m

Use `drawViewHierarchyInRect` if UIWindow have that method.
see also
https://developer.apple.com/library/ios/qa/qa1817/_index.html

add rendering method for WriteScreenShot

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m

Needed this for some of our test cases.

Add support for clearing the first responder

---

Additions/UIView-KIFAdditions.h
Additions/UIView-KIFAdditions.m
KIF Tests/MultiFingerTests.m

This adds a two finger tap gesture and associated tests.
I also removed gesture recognizers from the tests once they were done in case they caused side effects with future tests.

Added two finger tap gesture

---

Classes/KIFTypist.m

This pull request fixes kiftypist behaviour on device with split keyboards. The manifestation was that enterTextIntoFirstResponder will fail when on device with split keyboard, because the UIKeyboardWillShowNotification never gets fired under those circumstances.

fix typist to work on device with split keyboards

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m

* making swipeViewWithAccessibilityLabel:_ reusing swipeAccessibilityElement
* following the same pattern as tap, wait and scroll.

introducing swipeAccessibilityElement to provide ability for complex logic

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m

Created a new pull request with only the specific commit.

Added swipeRowAtIndexPath:inTableView:inDirection: method

---

KIF.xcodeproj/xcshareddata/xcschemes/KIFFramework.xcscheme

Remove test host reference

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
Classes/UIAutomationHelper.h
Classes/UIAutomationHelper.m
KIF Tests/BackgroundTests.m
KIF.xcodeproj/project.pbxproj
Test Host/BackgroundViewController.m
Test Host/en.lproj/MainStoryboard.storyboard

Had some merge conflicts when I pulled in recent master and felt it was easier to create a new pull request. This adds backgrounding to the app same as before.

Added backgrounding to app.

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
IdentifierTests/KIFUITestActor-IdentifierTests.h
IdentifierTests/KIFUITestActor-IdentifierTests.m
KIF Tests/AccessibilityIdentifierTests.m
KIF Tests/TappingTests.m
Test Host/TapViewController.m
Test Host/en.lproj/MainStoryboard.storyboard

adds in functionality for:
tapStepperWithAccessibilityLabel
tapStepperWithAccessibilityIdentifier
Adds new tapping test cases for the same.
To support the test cases new UI elements (A UIStepper and a UILabel)
were added to the storyboard.

Adding in new test methods for UIStepper

---

Additions/SenTestCase-KIFAdditions.m
Additions/XCTestCase-KIFAdditions.m
Classes/KIFTestCase.m

Hello, guys!
This pull request is related to #598.

Added screenshot saving upon failure when using KIF with Specta

---

.travis.yml

Based on: https://github.com/Homebrew/homebrew/issues/45616

Adding in a small hack for travis build.

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
IdentifierTests/KIFUITestActor-IdentifierTests.h
IdentifierTests/KIFUITestActor-IdentifierTests.m
KIF Tests/AccessibilityIdentifierPullToRefreshTests.m
KIF Tests/PullToRefreshTests.m
KIF.xcodeproj/project.pbxproj
Test Host/TestSuiteViewController.m

New Pull To refresh convenience methods and associated test cases that can also serve as an example of how the methods can be used.

Add new pullToRefresh methods with associated label and identifier tests

---

README.md

Changed maximum supported version

Fixed iOS 9 support in Readme

---

IdentifierTests/KIFUITestActor-IdentifierTests.m

Similar to https://github.com/kif-framework/KIF/pull/759

Send 0 instead of nil as pullDownDuration fixing compilation error

---

Test Host/TableViewController.m
Test Host/en.lproj/MainStoryboard.storyboard

Fix search bar test to explicitly set autocapitalizationType

---

Test Host/TableViewController.m

Thanks @phatmann for catching this in #773

Remove nullable

---

KIF Tests/ModalViewTests.m

Fix modal tests to pass on iPads

---

.travis.yml
KIF Tests/BackgroundTests.m
KIF Tests/ModalViewTests.m

All the test issues that I'm addressing in my other PRs should be covered by increasing the automated test matrix a bit. This will show the issues those PRs are addressing as well as ensure they don't regress in the future. 
This shouldn't be merged until #777, #776, #775, #774, #773, #772, #771 are all merged, and this PR has been rebased to show that Travis will go green.

Improve Travis test coverage

---

Classes/KIFUITestActor.m

related to this comment: https://github.com/kif-framework/KIF/issues/799

Added UIPickerView attributed string support

---

Additions/UIScreen+KIFAdditions.h
Additions/UIScreen+KIFAdditions.m
Classes/KIFUITestActor.h
KIF Tests/Additions/UIScreen+KIFAdditionsTests.m
KIF.xcodeproj/project.pbxproj

Value is set so that the previous value of 200pts is maintained for screens that are 320pts wide.
Fix #601

Define `kKIFMajorSwipeDisplacement` proportionally to screen width

---

Classes/KIFUIViewTestActor.h

This new class just got merged, so I thought it prudent to write some documentation.

added documentation for the new KIFUIViewTestActor

---

Classes/KIFUIViewTestActor.m

This was missing before, sorry about that.

added predicate description for [KIFUIViewTestActor usingValue:]

---

Classes/KIFTestActor.h
Classes/KIFUITestActor.h

We compile with `-Wdocumentation` and found a few small issues while using KIF to test PSPDFKit.
Thanks for making this - it's very useful!

Fixes various small documentation issues

---

Additions/XCTestCase-KIFAdditions.m

Allow opting into having the full view hierarchy dumped on failure. Seeing some discrepancies between my local environment and our CI system, and thought this would help to figure out what's going on.

Add some additional debugging on failure

---

Classes/KIFUITestActor.h
Classes/KIFUITestActor.m
KIF Tests/TypingTests.m

Utility function which works with labels, text views and text fields.
Allows to assert on expected text after typing in.

Added textFromView: function to assert on expected text

---

Classes/KIFUITestActor.m

Currently, if an test **swipes/scrolls** a view, KIF first waits for an accessibility element (UIAccessibilityElement) and the according view, which should the be swiped/scrolled afterwards.
However, in my case (older version of KIF) ```waitForAccessibilityElement:view:withIdentifier:tappable:``` returned a **valid view**, but the **accessibility element** was still **nil** afterwards. Therefore ```swipeAccessibilityElement:inView:inDirection:``` always used a start point with origin:(0,0), width:0, height:0 (accessibilityFrame of accessibility element - nil).
This **zero start point** lead to failing tests, because side navigation bar got swiped (from screen border) instead of the specified view (center of view). As the documentation says *"... and swipe the screen in the given direction …

Accessibility Frame Fallback

---

Classes/UIAutomationHelper.m

Somtimes, alert created from app may trigger exception, this patch catch it.

catch occasional exception

---

Additions/UIView-KIFAdditions.m

Converts coordinates from view coordinates to be relative to the window.

Convert paths to be in window coordinates before we start moving the window

---

Additions/UIApplication-KIFAdditions.m

When we find a hidden window nothing should be visible beyond that view.

Don't enumerate hidden windows

---

Documentation/Examples/Testable Swift/Testable Swift.xcodeproj/project.pbxproj
Documentation/Examples/Testable Swift/Testable Swift.xcodeproj/xcshareddata/xcschemes/Testable Swift.xcscheme
Documentation/Examples/Testable Swift/Testable Swift/Base.lproj/Main.storyboard
Documentation/Examples/Testable Swift/Testable Swift/Images.xcassets/AppIcon.appiconset/Contents.json
Documentation/Examples/Testable Swift/Testable Swift/MasterViewController.swift
Documentation/Examples/Testable Swift/Testable SwiftTests/SimpleSwiftTest.swift
Documentation/Examples/Testable Swift/Testable SwiftTests/Testable_SwiftTests.swift

- Testable Swift Project updated to Swift-3.0 and Xcode-8 Project-Settings
- TableView filled programmatically
- Adding Test for AccessibilityIdentifiers

Testable Swift Project updated (Swift-3.0)

---

Additions/UIAccessibilityElement-KIFAdditions.m
KIF Tests/TableViewTests.m
KIF Tests/TableViewTests_ViewTestActor.m
Test Host/en.lproj/MainStoryboard.storyboard

Fix scrolling to cells that are under a translucent toolbar (#953)

---

Test Host/en.lproj/MainStoryboard.storyboard

This should fix the Travis CI failures introduced in #952.

Fix MainStoryboard compilation on Xcode 7

---

Documentation/Examples/Calculator/Acceptance Tests/Acceptance Tests-Prefix.pch
Documentation/Examples/Calculator/Acceptance Tests/BasicCalculatorTests.m
Documentation/Examples/Calculator/Acceptance Tests/KIFUITestActor+BasicCalculator.h
Documentation/Examples/Calculator/Acceptance Tests/KIFUITestActor+BasicCalculator.m
Documentation/Examples/Calculator/Calculator.xcodeproj/project.pbxproj
Documentation/Examples/Calculator/Calculator.xcodeproj/xcshareddata/xcschemes/Calculator.xcscheme
Documentation/Examples/Testable Swift/Testable Swift.xcodeproj/project.pbxproj
Documentation/Examples/Testable Swift/Testable SwiftTests/SimpleObjCTest.m
Documentation/Examples/Testable Swift/Testable SwiftTests/SimpleSwiftTest.swift
Documentation/Examples/Testable/Acceptance Tests/Acceptance Tests-Prefix.pch
Documentation/Examples/Testable/Acceptance Tests/IntegrationTestCases.m
Documentation/Examples/Testable/Acceptance Tests/KIFUITestActor+EXAddition.h
Documentation/Examples/Testable/Acceptance Tests/KIFUITestActor+EXAddition.m
Documentation/Examples/Testable/Acceptance Tests/en.lproj/InfoPlist.strings
Documentation/Examples/Testable/Testable.xcodeproj/project.pbxproj
Documentation/Examples/Testable/Testable.xcodeproj/xcshareddata/xcschemes/Testable.xcscheme
KIF.xcodeproj/project.pbxproj
scripts/ci.sh

Fixes #970
Also, updated it to use the examples to use the v3 API that @RoyalPineapple introduced.
CC: @imsrc21 @phatmann

Fix Example Projects and run them via CI

---

Classes/KIFSystemTestActor.h
Classes/KIFSystemTestActor.m

Silences new warnings that appear in Xcode 9

Xcode 9 build warnings

---

Classes/KIFUITestActor.m
KIF Tests/CustomPickerTests.m
KIF Tests/CustomPickerTests_ViewTestActor.m
KIF.xcodeproj/project.pbxproj
Test Host/CustomPickerController.m
Test Host/en.lproj/MainStoryboard.storyboard

KIF fails in "selectPickerViewRowWithTitle" if UIPickerView having a custom label for title view

KIF fails in "selectPickerViewRowWithTitle"

---

scripts/ci.sh

Only build Calculator demo target, skip testing due to #1046

---

Classes/KIFAccessibilityEnabler.h
Classes/KIFAccessibilityEnabler.m
Classes/KIFTestActor.m

Crash on using a test actor unless KIFEnableAccessibility has already been called

---

scripts/ci.sh

Fixes #1055.
CC: @wedkarz @Prince2k3

Make sure that we can't break Carthage releases in the future

---

.travis.yml
Additions/UIView-KIFAdditions.m
KIF Tests/PickerTests.m
KIF Tests/PickerTests_ViewTestActor.m
Test Host/PickerController.m

Fixes #1007
Trying out a fix for issue #1007.
@justinseanmartin @RoyalPineapple please have a look?
Thanks to Larry Gensch (non-github user at this time) who did all of the heavy lifting.
Thanks,
Mike

Fix for "Attempted to dequeue multiple cells for the same index path" in table views with Xcode 9

---

Classes/KIFUITestActor.h

// as is
**heirarchy.**
// to be
**hierarchy** 👻

Edit mistyping on KIFUITestActor.h

---

Additions/XCTestCase-KIFAdditions.m

Add support for Xcode 12. I encountered compilation failures when building this dependency with Carthage.

Fix compilation issue for Xcode 12

---

KIF.podspec

Update KIF version to 3.7.10

---

KIF.podspec

@dostrander mind cutting a release with this change?

Specify in podspec that KIF depends on WebKit

---

Additions/UIView-Debugging.m
Visualizer/KIFEventVisualizer.h
Visualizer/KIFEventVisualizer.m
Visualizer/KIFTouchVisualizerView.m
Visualizer/KIFTouchVisualizerViewCoordinator.h
Visualizer/KIFTouchVisualizerViewCoordinator.m

This Fixes an issue that arises when switching windows and changing first responder due to visualizer.

Add visualizer to top window instead of a seperate window

---

KIF.podspec

Bumps minor version of KIF due to https://github.com/kif-framework/KIF/pull/1209

Bump KIF 3.8.0

---

KIF.podspec

Update KIF to 3.8.9

---

Sources/KIF/Classes/KIFSystemTestActor.m

See notes on https://developer.apple.com/documentation/uikit/uiinterfaceorientation

Fixed device orientation to interface orientation

---

.github/workflows/build.yml

MacOS latest image removed Xcode 16.0.  Updating to Xcode 16.1

Updated to Xcode 16.1

---

Sources/KIF/Classes/KIFUITestActor.h
Sources/KIF/Classes/KIFUITestActor.m
Sources/KIF/Classes/KIFUIViewTestActor.h
Sources/KIF/Classes/KIFUIViewTestActor.m

Expanded the api for entering text to allow for delaying between typing characters.

Add character typing delay option for enter text

---

KIF.podspec

Bumped the pod version to 3.11.0

Bump version to 3.11.0
